### ISSUE TITLE
T194 and T234 support

### ISSUE THREAD

**Issue by leonpano2006** [Pi-Apps-Coders/box64-debs#2]
I made update in my site
Is possible to use gcc-9 for t194?
Or it will error on compile

For t234 I choose gcc-13 since for that you need ppa:ubuntu-toolchain-r/test anyway for gcc-11+

**Comment by theofficialgman** [comment]
No observable performance improvement for the tuned builds as of now so there is no plan to add a tuned build for these systems (at least until GitHub has ARM runners available for free) as it would require a major rewrite of the CI for no benefit.
